FROM ubuntu:23.10
LABEL maintainer="nekonado@example.com"

ARG builddate
ENV BUILDDATE=${builddate}
ENV BUILDFROM="from Ubuntu"

# ENTRYPOINT ["/bin/bash", "-c"]
# CMD ["env"]
CMD ["/bin/bash", "-c", "env"]